// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Config 是 VLM 那一份配置。
 * 
 * 它**不进 SQLite**。三个理由，按重要性排：
 * 
 *   - 配置与凭据本来就不属于错题的数据模型。ADR-0004 已经把「库外的东西」这个模式立在了
 *     图片上（库不膨胀、备份不变慢），这里是同一个道理。
 *   - 凭据不该跟着导出包一起被打包、被复制来复制去。
 *   - 顺带的：库的迁移这会儿正被别的改动追加着，为一份配置去抢那一行不值当。
 * 
 * 落点是应用私有目录下的一个 JSON 文件，与 library.db、cards/ 并列
 * （目录来自 main.go 的 dataDir()，路径由接线时传进来）。
 * 
 * 模型名**必须**由这里给（ADR-0005：不得硬编码模型 ID）。所以本包在代码里找不到任何
 * 默认模型名：空着就是没配置，调模型的动作会明确报 ErrNotConfigured，
 * 而不是偷偷用一个写死的名字跑起来。
 */
export interface Config {
    /**
     * BaseURL 是服务方的接入点，不带尾部斜杠。OpenAI 兼容的那几个端点都挂在它下面
     * （对话是 /chat/completions，文件是 /files）。
     */
    "base_url": string;

    /**
     * APIKey 是凭据。**绝不写进日志、报错或界面**：要报告它的存在，只说有没有、多长。
     */
    "api_key": string;

    /**
     * VisionModel 是能看图的模型名：打标签、就题讨论都走它。
     */
    "vision_model": string;

    /**
     * TextModel 是纯文本的模型名，没有图片的流量走它。
     * 
     * 留这一路是因为视觉模型带 Exp 后缀、官方声明可能被替换，而纯文本那边的活
     * （agent 整理数据、推荐今天做几道）不需要跟着它一起冒险。
     */
    "text_model"?: string;

    /**
     * Detail 是内联传图时的高保真档位，取值见 Detail* 那几个常量。
     * 
     * 空着按 original 发（见 detailOrDefault）：票据要求**显式**请求高保真 ——
     * 题面是密集文档，降到 512×512 就看不清了，而这种事不该指望服务方的默认值不变。
     */
    "detail"?: string;

    /**
     * TagPrompt 是打标签的提示词，空着用内置的那份（见 prompt.go）。
     * 
     * 留这个口子是因为打标签的质量还没有定论（票据 01），措辞要能不改代码就换 ——
     * 真机上试一版措辞比重新构建一个 APK 快得多。
     */
    "tag_prompt"?: string;
}

/**
 * ConfigView 是配置的「界面版」：**没有凭据的值**。
 * 
 * 凭据只进不出。界面要知道的是「配没配」，够用的是有没有与多长，不是那串东西本身 ——
 * 票据的硬约束：绝不在代码、注释、日志或界面里打印凭据的值。
 */
export interface ConfigView {
    /**
     * Path 是配置文件的落点。显示出来，是因为安卓上这个路径用户平时够不着，
     * 出问题时至少知道该去哪儿找。
     */
    "Path": string;

    /**
     * Configured 为真表示这份配置已经能拿去调模型。
     */
    "Configured": boolean;
    "BaseURL": string;
    "VisionModel": string;
    "TextModel": string;
    "Detail": string;

    /**
     * APIKeySet / APIKeyLength 是凭据的**存在性**与长度，不是它的值。
     */
    "APIKeySet": boolean;
    "APIKeyLength": number;

    /**
     * Problem 非空时说明这份配置为什么还不能用（缺了哪一项）。
     */
    "Problem": string;
}

/**
 * Image 是要交给模型看的一张图。
 */
export interface Image {
    /**
     * Hash 是这张图在本地的内容 hash（ADR-0004 的名字：图片按内容 hash 命名）。
     * 它是「这张图传上去过没有」的键 —— 同一张题图会在打标签与讨论两条路径上反复用到，
     * Files API 的全部意义就是别传第二遍。
     */
    "Hash": string;

    /**
     * Data 是图片的原始字节。这里恒为 PNG：题图落盘就是 PNG，读回来的也是 PNG。
     */
    "Data": string | null;

    /**
     * MIME 是它的媒体类型，形如 image/png。
     */
    "MIME": string;

    /**
     * FileID 非空表示这张图已经传到服务方了，这次用引用而不是内联 base64。
     * 由调用方（Service）填：怎么拿到这个引用的（缓存命中 / 刚传的 / 传不上去）是**策略**，
     * Provider 只负责照着它决定报文长什么样。
     */
    "FileID": string;
}

/**
 * Message 是一条消息。
 */
export interface Message {
    "Role": Role;
    "Text": string;

    /**
     * Images 只能挂在 user 消息上 —— 服务方的硬约束：放进 system 或 assistant 直接 400。
     * 类型上没拦这一条（拦了就得为每种能带图的角色各造一个类型），由 Service 拼消息时守住。
     */
    "Images": Image[] | null;
}

/**
 * ProposedTag 是**一条**分层标签建议：学科 > 章节 > 知识点。
 * 
 * 它还没落库。它既可能来自模型，也可能是用户在界面上改过之后的版本 ——
 * 两者形状完全一样，因为「改完的」才是最终要保存的东西。
 * 
 * 章节或知识点可以是空串：模型定不下来时留空，是**合法**的中间状态
 * （与标签包那边「先搭骨架再往里填」一致）。学科不能空 —— 空了就不知道该挂到哪棵树下。
 */
export interface ProposedTag {
    "Subject": string;
    "Chapter": string;
    "Point": string;
}

/**
 * Reply 是模型的一次回答。
 */
export interface Reply {
    "Text": string;
}

/**
 * Role 是一条消息的角色。取值直接就是线上报文里的样子（user / assistant / system），
 * 不另立一套自己的枚举再到实现里翻译一遍 —— 这一层抽象要挡的差异不在这里。
 */
export enum Role {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleSystem = "system",
    RoleUser = "user",
    RoleAssistant = "assistant",
};

/**
 * TagSuggestion 是「让 VLM 给这道题打标签」这一次的结果。
 */
export interface TagSuggestion {
    "QuestionID": number;

    /**
     * Tags 是模型给的建议，空切片而不是 nil（前端要拿到 []，不是 null）。
     */
    "Tags": ProposedTag[] | null;

    /**
     * Raw 是模型的原话。解析成功时它也在 —— 人工核对「它是不是真这么说的」时有用，
     * 票据 01 要评的就是它的质量。它**没有**凭据，模型看不到也不该看到凭据。
     */
    "Raw": string;

    /**
     * Problem 非空表示这次调用成功了，但结果不能用：模型没按约定的 JSON 回，
     * 或者回了空集（它自己也没主意）。此时 Tags 是空的，而 Raw 里是它说的原话。
     * 
     * 为什么它是字段而不是 error：Wails 那边 error 会把返回值一起丢掉，
     * 而这里恰恰**要把模型的原话交给用户看** —— 调提示词全靠那句原话。
     * 真正的调用失败（没配置、网络、401）仍然是 error，走的仍是另一条路。
     */
    "Problem": string;
}
