// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「VLM 打标签」对前端暴露的那一面，也是本包唯一的测试缝
 * （spec：全应用只有一条缝，在服务层 —— 调用它、断言它的返回与它落库的结果）。
 * 
 * 它做的是一件完整的事：取题图 → 交给 provider（能复用引用就复用）→ 拿回分层标签 →
 * **先给用户改** → 用户点了保存才落成一棵真的标签树并挂到题上。
 * 
 * 「先给用户改」是硬的：SuggestTags 一个字节都不写库，SaveTags 才写。
 * 所以这一层有两半，中间隔着一次人的决定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tags$0 from "../tags/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Config 返回配置的「界面版」：**不含凭据的值**，只说有没有、多长。
 */
export function Config(): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(2355078181);
}

/**
 * SaveTags 把（用户改过的）这份建议落成一棵真的标签树，并整份挂到这道题上。
 * 
 * 这是「保存后才生效」的那一步，也是本包唯一会写库的地方。缺的标签现建：
 * 名字在（父, 名字）这一对上找不到就建一个。已经有的照用，不新建 ——
 * 所以用户反复用同一批标签时，词表不会长出一堆同名节点。
 * 
 * 挂上去的是**整条路径**（学科 + 章节 + 知识点），不是只有叶子。理由是跟另一条入口对齐：
 * 手工打标签那个勾选面板勾一个知识点时会连带它的父一起勾上（见 TagFilter.svelte），
 * 两条路挂出来的东西得是同一个形状，否则「这道题有几个标签」这个数会随入口不同而不同。
 * 
 * 返回落库之后这道题真实的标签集。
 */
export function SaveTags(questionID: number, proposed: $models.ProposedTag[] | null): $CancellablePromise<tags$0.Tag[] | null> {
    return $Call.ByID(1649819163, questionID, proposed);
}

/**
 * SetConfig 把配置写下去并立刻生效（换 key、换模型、试提示词都不必重启）。
 * 
 * 传进来的那份是**补丁**不是整份：空字符串表示不动这一项。这不是为了省事 ——
 * 界面拿不到凭据的值（本包从不把它读出去），所以它改别的项时没法把 key 原样带回来。
 * 要清空某一项就删掉配置文件重来。
 * 
 * 先验再写：一份缺项的配置存下去也用不了，不如当场退回，别让它躺在盘上冒充「配好了」。
 */
export function SetConfig(patch: $models.Config): $CancellablePromise<void> {
    return $Call.ByID(3755431663, patch);
}

/**
 * SuggestTags 让 VLM 给一道错题拟一份分层标签。
 * 
 * **只读**：不建标签、不往题上挂任何东西。票据要求这些建议先交给用户改、
 * 保存之后才生效 —— 那一步是 SaveTags。所以这个方法可以随便重试，不会留下痕迹。
 * 
 * 题不存在返回 library.ErrNotFound；没配 VLM 返回 ErrNotConfigured；
 * 模型给了不能用但调用成功的结果时 error 为 nil，看 TagSuggestion.Problem。
 */
export function SuggestTags(questionID: number): $CancellablePromise<$models.TagSuggestion> {
    return $Call.ByID(682326230, questionID);
}
