// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「VLM 打标签」对前端暴露的那一面，也是本包唯一的测试缝
 * （spec：全应用只有一条缝，在服务层 —— 调用它、断言它的返回与它落库的结果）。
 * 
 * 它做的是一件完整的事：取题图 → 交给 provider（能复用引用就复用）→ 拿回分层标签 →
 * **先给用户改** → 用户点了保存才落成一棵真的标签树并挂到题上。
 * 
 * 「先给用户改」是硬的：SuggestTags 一个字节都不写库，SaveTags 才写。
 * 所以这一层有两半，中间隔着一次人的决定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tags$0 from "../tags/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Ask 是「就一道错题跟模型说一句」这条接缝，也是讨论那一侧唯一的入口。
 * 
 * 为什么它开在这儿而不是开在讨论包里：这边已经握有那三样东西 —— 配置与 provider 的选法、
 * 题图的读法、以及 hash → file_id 的**上传缓存**。讨论每一轮都要把题图（与答案图，如果有）
 * 送上去，缓存不共用就等于每轮重传一遍（票据的硬要求）；而重做一遍取配置、拼报文、
 * 回落内联那套，只是把同一个东西抄成两份，两边迟早会走偏。
 * 
 * history 是**整段对话**，最后一条必须是要问出口的那句（用户消息）。这一层不动它的顺序与
 * 内容，只做两件事：把这一轮的图挂到最后一条 user 消息上，然后发出去。
 * 
 * 图挂在**最后**一条 user 消息上，不挂在第一条：一次请求里只带一份，不随轮数翻倍；
 * 它又紧挨着这次的问题，将来做历史截断时也不会因为「开头那条被丢掉」而把图弄丢。
 * 代价是每一轮都重发一次图（服务方那边一张图最多算 1024 token），换来的是模型每一轮
 * 都真的看着这张图在答。图走的是与打标签**同一份**缓存：同一张题图只上传一次。
 * 
 * 题不存在返回 library.ErrNotFound；没配 VLM 返回 ErrNotConfigured；网络与凭据的问题
 * 由 provider 原样报上来。
 */
export function Ask(questionID: number, history: $models.Message[] | null): $CancellablePromise<$models.Reply> {
    return $Call.ByID(1424447240, questionID, history);
}

/**
 * AskText 是「问模型一句**不带图**的话」这条接缝 —— 推荐今日复习量走它。
 * 
 * 为什么与 Ask 分开、而不是给它加一个「这次不带图」的开关：两条路要的东西不一样。
 * 讨论必然带图，于是要读题图与答案图、要过那份 hash → file_id 的上传缓存；这条路手上
 * 只有几个数，没有图可传，那套东西一样都用不上。合在一起就得在 Ask 里到处问「这次有图吗」。
 * 
 * 走的是配置里的**文本模型**那一路（Config.modelFor）：视觉模型带 Exp 后缀、官方声明可能
 * 被替换，而推荐复习量这种纯文本的活不该跟着它一起冒险 —— 这正是 Config.TextModel 留着
 * 的原因（它的注释里点名了「推荐今天做几道」）。文本模型没配时回落到视觉模型，见 textModel。
 * 
 * 回答要求是 JSON 对象：这条路眼下唯一的用处是「要一个数」，而散文里挑数是挑不出来的。
 * 将来有别的纯文本活要自由文本（比如 agent 那边的整理），再加旋钮，现在不猜。
 * 
 * 没配 VLM 返回 ErrNotConfigured；网络与凭据的问题由 provider 原样报上来。
 */
export function AskText(system: string, user: string): $CancellablePromise<$models.Reply> {
    return $Call.ByID(11313647, system, user);
}

/**
 * Config 返回配置的「界面版」：**不含凭据的值**，只说有没有、多长。
 */
export function Config(): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(2355078181);
}

/**
 * SaveTags 把（用户改过的）这份建议落成一棵真的标签树，并整份挂到这道题上。
 * 
 * 这是「保存后才生效」的那一步，也是本包唯一会写库的地方。缺的标签现建：
 * 名字在（父, 名字）这一对上找不到就建一个。已经有的照用，不新建 ——
 * 所以用户反复用同一批标签时，词表不会长出一堆同名节点。
 * 
 * 挂上去的是**整条路径**（学科 + 章节 + 知识点），不是只有叶子。理由是跟另一条入口对齐：
 * 手工打标签那个勾选面板勾一个知识点时会连带它的父一起勾上（见 TagFilter.svelte），
 * 两条路挂出来的东西得是同一个形状，否则「这道题有几个标签」这个数会随入口不同而不同。
 * 
 * 返回落库之后这道题真实的标签集。
 */
export function SaveTags(questionID: number, proposed: $models.ProposedTag[] | null): $CancellablePromise<tags$0.Tag[] | null> {
    return $Call.ByID(1649819163, questionID, proposed);
}

/**
 * SetConfig 把配置写下去并立刻生效（换 key、换模型、试提示词都不必重启）。
 * 
 * 传进来的那份是**补丁**不是整份：空字符串表示不动这一项。这不是为了省事 ——
 * 界面拿不到凭据的值（本包从不把它读出去），所以它改别的项时没法把 key 原样带回来。
 * 要清空某一项就删掉配置文件重来。
 * 
 * 先验再写：一份缺项的配置存下去也用不了，不如当场退回，别让它躺在盘上冒充「配好了」。
 */
export function SetConfig(patch: $models.Config): $CancellablePromise<void> {
    return $Call.ByID(3755431663, patch);
}

/**
 * SuggestTags 让 VLM 给一道错题拟一份分层标签。
 * 
 * **只读**：不建标签、不往题上挂任何东西。票据要求这些建议先交给用户改、
 * 保存之后才生效 —— 那一步是 SaveTags。所以这个方法可以随便重试，不会留下痕迹。
 * 
 * 题不存在返回 library.ErrNotFound；没配 VLM 返回 ErrNotConfigured；
 * 模型给了不能用但调用成功的结果时 error 为 nil，看 TagSuggestion.Problem。
 */
export function SuggestTags(questionID: number): $CancellablePromise<$models.TagSuggestion> {
    return $Call.ByID(682326230, questionID);
}
