// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Recommendation 是一次推荐的结果。
 * 
 * 它**不是**一条新的到期时间，也不是对队列的修改：它只是「今天再做几道」这个数。
 */
export interface Recommendation {
    /**
     * Suggest 是建议今天再做的道数，恒在 [1, Due] 之内。
     * 
     * 0 只有一个意思：**没有可推荐的东西** —— 队列已经空了（今天一道都没到期，或者
     * 都做完了）。那时不会去调模型（见 Recommend），界面也不该显示这一条。
     */
    "Suggest": number;

    /**
     * Due 是这次推荐时**队列里还有多少道**。
     * 
     * 「今天到期多少」与「还剩多少」在这个应用里是同一个数：评过的题被 FSRS 推到至少
     * 明天之后（review.newScheduler 关掉学习步就是为了这条），所以做完一道它就少一道。
     * 把模型看到的那个数带出来，界面上就不必拿队列长度去猜 —— 用户做掉一道之后，
     * 界面上那个长度与模型当时看到的就不是同一个数了。
     */
    "Due": number;

    /**
     * Reason 是模型给的一句话理由，可能为空（它没给，或者给了一堆空白）。
     * 界面上要显示它：用户得看得出这个数是怎么来的，才谈得上采纳或不采纳。
     */
    "Reason": string;
}
