// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「今天建议再做几道」对前端暴露的那一面，也是本包唯一的测试缝（见 spec）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Recommend 让模型看着「现在还剩多少道」与「最近的表现」，给一个今日复习量。
 * 
 * **只读**：不碰队列、不碰 review_states、不碰 review_logs。这一点是这一票的验收里
 * 最要紧的一条 —— 推荐只是一个数，用户不采纳时一切照旧。
 * 
 * 队列空时不调模型，直接回一个 Suggest 为 0 的结果：没有可推荐的东西，为此发一次请求
 * 既是白花钱，也会让「今天没有要复习的题」这一屏莫名其妙地转一会儿圈。
 * 
 * 拿不到推荐时一律是 error，界面据此**静默退化**：没配 VLM 是 vlm.ErrNotConfigured、
 * 断网是 provider 报上来的错、模型答得不能用是 ErrUnusableAnswer。推荐是锦上添花，
 * 不能变成单点故障。
 */
export function Recommend(): $CancellablePromise<$models.Recommendation> {
    return $Call.ByID(2600265249);
}
