// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * bundleStager 是给前端的导出那一面。
 * 
 * 为什么不直接把 *export.Service 注册上去：它还有 WriteBundle(io.Writer)，而 Wails 要拿
 * 导出的方法生成 TS 绑定 —— 一个 io.Writer 形参在 TS 那边没有对应的东西。所以这层只把
 * 界面用得上的 Stage 露出去；打包本身照旧在 export.Service 里，这层纯粹是绑定边界。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as export$0 from "./internal/export/models.js";

export function Stage(): $CancellablePromise<export$0.Bundle> {
    return $Call.ByID(1697802194);
}
