// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * deviceTime 是给前端的一个小服务：把**设备时区**告诉 Go。
 * 
 * 为什么需要这么一条：Go 在安卓上拿不到系统时区（time.Local 就是 UTC），而所有「今天」
 * 都建在它上面 —— 复习队列的今日到期、每日汇总的发车时刻。WebView 那边知道得清清楚楚
 * （Intl.DateTimeFormat().resolvedOptions().timeZone），所以由前端启动时告诉 Go 一次。
 * 见 internal/devtz 的包注释。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Get 报告当前记着的时区名；空串表示还没被设过（此时用的是 time.Local，安卓上即 UTC）。
 */
export function Get(): $CancellablePromise<string> {
    return $Call.ByID(3295588755);
}

/**
 * Set 记住设备时区（IANA 名，如 "Asia/Shanghai"），返回记下的那个。
 */
export function Set(zoneID: string): $CancellablePromise<string> {
    return $Call.ByID(4023078215, zoneID);
}
