// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Message 是讨论里的一条记录。
 */
export interface Message {
    /**
     * ID 落库时分配。它同时是同一毫秒内两条记录的先后依据（见 Store.history）。
     */
    "ID": number;

    /**
     * QuestionID 是它挂在哪道错题上。
     */
    "QuestionID": number;

    /**
     * Role 是谁说的。
     */
    "Role": Role;

    /**
     * Text 是说了什么。
     */
    "Text": string;

    /**
     * CreatedAt 是这句话的时刻，落库时截到毫秒（UTC）。
     */
    "CreatedAt": string;
}

/**
 * Role 是一条记录是谁说的。
 * 
 * 取值与 vlm.Role 逐字相同（user / assistant）：它要原样进 vlm.Message、也要原样进
 * 库里的 role 列，中间不该隔一张对照表。所以下面两个常量**由 vlm 的那两个值定义** ——
 * 哪边改了，这边编译就过不去，两个包不可能悄悄跑偏。
 */
export enum Role {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleUser = "user",
    RoleAssistant = "assistant",
};

/**
 * Turn 是刚过去的一轮问答：用户问的那句，和模型答的那句。
 * 
 * 两条都已经落库了 —— 带回来只是省得界面再回库读一次。
 */
export interface Turn {
    /**
     * 用户这一句
     */
    "Question": Message;

    /**
     * 模型的回答
     */
    "Reply": Message;
}
