// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「讨论」对前端暴露的那一面，也是本包唯一的测试缝（见 spec）。
 * 
 * 它持有一条错题库连接（讨论与错题同一份库文件）与题库本身 —— 写之前要确认这道题在，
 * 那条查询在 library 那边，不必在本包再抄一遍 SQL。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Ask 就一道错题问一句：先记下用户这句，再交给 VLM，把回答也记下。
 * 
 * **用户那句先落库，顺序在实现里而不只是在注释里。** 模型调用可能断网、超时、没配 key，
 * 那些失败都不该把用户打的字带走（票据 33：讨论时被打断的人，讨论记录不会丢）。
 * 代价是失败之后讨论里会留下一条没有回应的用户消息 —— 那是如实的，他确实问了，
 * 而模型确实没答上来；界面上重读一次 History 就能看到，再问一次即可。
 * 
 * 失败时返回零值 Turn 与错，只有前两种不落任何写入：
 *   - 要问的是空的 → ErrEmptyMessage
 *   - 题不存在 → library.ErrNotFound
 *   - 模型没回答（空文本）→ ErrEmptyReply
 *   - 没配 VLM / 网络 / 服务方报错 → provider 那边原样冒上来
 */
export function Ask(questionID: number, text: string): $CancellablePromise<$models.Turn> {
    return $Call.ByID(3866921011, questionID, text);
}

/**
 * History 返回一道错题的讨论记录，从早到晚（同一毫秒内按落库先后）。
 * 
 * 题不存在时返回空集而不是报错：这是个读，界面拿一个刚被删掉的 id 来问是正常的，
 * 看到「还没聊过」就够了（与 tags.TagsOfQuestion 同一条规矩）。写操作相反 —— 见 Ask。
 */
export function History(questionID: number): $CancellablePromise<$models.Message[] | null> {
    return $Call.ByID(3350200038, questionID);
}

/**
 * Presets 返回预设追问的文案，顺序即界面上的顺序。
 * 
 * 返回副本而不是那个切片本身：调用方改不动服务里的这一份。
 */
export function Presets(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2472319114);
}
