// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeleteResult 报告一次删除的波及面。
 * 
 * 删中间节点是**级联**的（见 Service.Delete），点一个节点删掉的东西可能不止一个 ——
 * 返回值就是用来在界面上把这件事说清楚的：「将一并删掉 2 个子标签、从 3 道错题上摘掉」。
 */
export interface DeleteResult {
    /**
     * 被删掉的标签数，含自身与全部子孙
     */
    "DeletedTags": number;

    /**
     * 有多少道错题因此少了至少一个标签（去重）
     */
    "UntaggedQuestions": number;
}

/**
 * Level 是标签的层级。固定三层：学科 > 章节 > 知识点。
 * 
 * 层级**存进库里**（tags.level）而不是每次爬上树现算。理由是固定三层是这套模型的硬约束：
 * 写成列，schema 层（CHECK）与服务层就都能拦住「知识点下面再挂一个」；按层级排序、
 * 取子树也都是顺手的事。代价是 level 必须与 parent_id 保持一致 —— 本包不提供「移动节点」，
 * 所以这个一致性不会被破坏（见 Service 的注释）。
 */
export enum Level {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * 学科
     */
    LevelSubject = 1,

    /**
     * 章节
     */
    LevelChapter = 2,

    /**
     * 知识点
     */
    LevelPoint = 3,

    /**
     * MaxLevel 是树的最大深度，也就是知识点那一层。
     */
    MaxLevel = 3,
};

/**
 * QuestionTags 是一道错题挂着的全部标签。批量取时用它把结果带回前端。
 */
export interface QuestionTags {
    "QuestionID": number;

    /**
     * 空切片而不是 nil：前端要拿到 []，不是 null
     */
    "Tags": Tag[] | null;
}

/**
 * Tag 是树上的一个标签。
 */
export interface Tag {
    /**
     * 落库时分配；Create 之前是 0
     */
    "ID": number;

    /**
     * 父标签的 id；0 表示顶层学科（库里存 NULL）
     */
    "ParentID": number;

    /**
     * 标签名，由用户自由填写
     */
    "Name": string;

    /**
     * 层级，由父节点推出来
     */
    "Level": Level;

    /**
     * 创建时间，落库时截到毫秒（UTC）
     */
    "CreatedAt": string;
}
