// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「标签」对前端暴露的那一面，也是本包唯一的测试缝（见 spec）。
 * 
 * 它持有一条错题库连接（标签与错题同一份库文件）与题库本身 —— 按标签筛错题要读
 * questions 表，那条查询在 library 那边（ListQuestionsTaggedWith）。
 * 
 * 这里**没有「移动节点」**：层级由父节点推出来，移动一个章节等于连同它整棵子树改层级
 * （或让层级与父子关系脱节），而这两种都不是现在需要的动作。要挪就删了重建。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddQuestionTag 给一道错题补挂一个标签。已经挂过就什么也不做（幂等）。
 */
export function AddQuestionTag(questionID: number, tagID: number): $CancellablePromise<void> {
    return $Call.ByID(3809228744, questionID, tagID);
}

/**
 * Create 在 parentID 下建一个标签，返回落库后的它。
 * 
 * parentID 传 0 表示建**顶层学科** —— 顶层由用户自由填写，本包只在新库里预置考研四门
 * 作初始值（迁移 2），预置的那些与用户后建的没有任何区别：可以改名，也可以删。
 * 
 * 层级由父节点推出来，不用调用方传：父是学科就只能建章节。父是知识点时返回 ErrMaxDepth，
 * 同级重名返回 ErrDuplicate，父不存在返回 ErrNotFound。
 */
export function Create(parentID: number, name: string): $CancellablePromise<$models.Tag> {
    return $Call.ByID(4084685165, parentID, name);
}

/**
 * Delete 删掉一个标签**连同它的整棵子树**，返回波及面。id 不存在时返回 ErrNotFound。
 * 
 * 为什么是级联，而不是把子节点提到被删节点的位置：三层是**语义**层级，不只是结构深度 ——
 * 「章节」的含义是「学科下的一块」，「知识点」是「章节里的一条」。把子节点提上来，等于让
 * 一条知识点去冒充章节（名字照旧，含义变了），层级与内容从此对不上；而且父节点下往往还有
 * 别的子节点，提上来的那批会挤进一个它们从没属于过的集合。反过来，「没有章节的学科」
 * 或「没有知识点的章节」是**合法**的中间状态（先搭骨架再往里填），所以级联不会留下
 * 不合法的树。
 * 
 * 代价是这一步是破坏性的：错题上挂的这些标签一并摘掉（错题本身不动），
 * 所以返回值里带上波及面，界面据此先问一句再删。
 */
export function Delete(id: number): $CancellablePromise<$models.DeleteResult> {
    return $Call.ByID(3948825530, id);
}

/**
 * List 返回全部标签，平铺。前端按 ParentID 自己拼树。
 */
export function List(): $CancellablePromise<$models.Tag[] | null> {
    return $Call.ByID(3320431761);
}

/**
 * QuestionsByTags 按标签筛错题，新的在前；多个标签取**并集**。
 * 
 * 筛选入口挂在标签服务上而不是题库服务上：它读的是 questions 表，但规则是标签树的 ——
 * 「点一个学科要带出它下面所有章节与知识点的题」属于树（见 library.Store.ListQuestionsTaggedWith）。
 * 
 * tagIDs 为空表示**不筛**，返回全部错题：界面上「一个标签都没勾」就是这个意思，
 * 于是筛与不筛是同一个调用，接线时不必分两条路。
 */
export function QuestionsByTags(tagIDs: number[] | null): $CancellablePromise<library$0.Question[] | null> {
    return $Call.ByID(3349781246, tagIDs);
}

/**
 * RemoveQuestionTag 从一道错题上摘掉一个标签。本来就没挂也什么也不做（幂等）。
 */
export function RemoveQuestionTag(questionID: number, tagID: number): $CancellablePromise<void> {
    return $Call.ByID(4173796155, questionID, tagID);
}

/**
 * Rename 改一个标签的名字，返回改完的它。id 不存在时返回 ErrNotFound。
 * 
 * 只改名字，不动它在树里的位置与层级 —— 见 Service 的注释（本包不做移动）。
 */
export function Rename(id: number, name: string): $CancellablePromise<$models.Tag> {
    return $Call.ByID(1033918147, id, name);
}

/**
 * SetQuestionTags 把一道错题挂着的标签**整体替换**成 tagIDs（空集 = 摘掉全部）。
 * 
 * 手工打标签在这一层就是一次替换：界面上是勾选，保存时把勾选结果整份交上来 ——
 * 比在前后端各维护一份增量稳妥。传入重复的 id 会被去重。
 * 
 * 题不存在返回 library.ErrNotFound，某个标签不存在返回 ErrNotFound；两种情况都不落任何写入。
 */
export function SetQuestionTags(questionID: number, tagIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(1562195386, questionID, tagIDs);
}

/**
 * TagsOfQuestion 返回一道错题挂着的标签，按层级排。
 * 
 * 题不存在时返回空集而不是报错：这是个读，界面拿一个刚被删掉的 id 来问是正常的，
 * 看到「没有标签」就够了。写操作相反 —— 见 SetQuestionTags。
 */
export function TagsOfQuestion(questionID: number): $CancellablePromise<$models.Tag[] | null> {
    return $Call.ByID(2048425369, questionID);
}

/**
 * TagsOfQuestions 一次取多道错题的标签，顺序与传入的 ids 一致（重复的会去掉）。
 * 
 * 列表页要为屏上每一行显示标签，一道题一次调用太浪费。
 * 没挂标签的题也会出现在结果里（Tags 为空切片），界面不必自己对齐。
 */
export function TagsOfQuestions(questionIDs: number[] | null): $CancellablePromise<$models.QuestionTags[] | null> {
    return $Call.ByID(512636766, questionIDs);
}

/**
 * UntaggedQuestions 返回**一条标签都没挂**的错题，新的在前。
 * 
 * 这是 QuestionsByTags 之外单独的一条，不是它的特例：那边的空数组含义是「不筛」，
 * 返回全部；而「未打标签」恰恰是个筛选条件（一个标签都没挂上），空数组表达不了。
 * 界面上的「未打标签」页签走的就是这里。
 */
export function UntaggedQuestions(): $CancellablePromise<library$0.Question[] | null> {
    return $Call.ByID(3191954599);
}
