// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Action 是一条待批准改动要干的事。
 * 
 * 取值就是 pending_changes.action 上那条 CHECK 约束写死的那几个字符串（迁移 5）——
 * 两边是一份契约的两半，改一处就得改另一处。库那侧也拦一道的意思很实在：
 * **别的种类的改动根本存不进来**，所以「agent 只能提议标签」不只是这一层写没写的问题。
 * 
 * 四样全是标签，因为 v1 的写范围就是标签（票据 11 钉的）。复习状态与删错题不在这里 ——
 * 不是还没做，是明确不做。
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 在某个父节点下新建一个标签
     */
    ActionCreateTag = "create_tag",

    /**
     * 给一个标签改名（不动它在树里的位置）
     */
    ActionRenameTag = "rename_tag",

    /**
     * 删一个标签，连同它的整棵子树
     */
    ActionDeleteTag = "delete_tag",

    /**
     * 把一道错题挂着的标签**整体换成**另一组
     */
    ActionTagQuestion = "tag_question",
};

/**
 * Answer 是「问一句」这一次的结果。
 */
export interface Answer {
    /**
     * Question 是原样收下的那句话，好让界面把它显示成这一轮的问句。
     */
    "Question": string;

    /**
     * Text 是模型的回答。为空的情形见 Problem。
     */
    "Text": string;

    /**
     * Proposals 是这一轮提议出来的待批准改动，空切片而不是 nil（前端要拿到 []，不是 null）。
     * 
     * 它们**已经在库里**了（提议那一刻就落了 pending_changes）。所以这一轮就算没答出话，
     * 用户也能在待批准列表里看到、逐条点头 —— 那份工作没有白做。
     */
    "Proposals": PendingChange[] | null;

    /**
     * Rounds 是实际跟模型往返了几轮（含用尽之后那次不带工具的收尾）。
     */
    "Rounds": number;

    /**
     * Problem 非空表示这次没给出正常回答：回合用尽了，或者模型一句话都没说。
     * 
     * 它是字段而不是 error，与 vlm.TagSuggestion.Problem 同一个理由：Wails 出错时会把
     * 返回值一起丢掉，而这里恰恰有东西要给用户看（已经提议出来的那几条改动）。
     * 真正的调用失败（没配置、网络、服务方报错）仍然是 error，走另一条路。
     */
    "Problem": string;
}

/**
 * Change 是**一条待批准改动的内容**：要干什么、拿什么参数干、以及两句给人看的话。
 * 
 * 它还没有身份（没有 id）也还没有状态 —— 那是落库之后才有的事，见 PendingChange。
 * 它同时也是 Applier 唯一的输入：写数据的那一步只认这个类型。
 */
export interface Change {
    "Action": Action;
    "Payload": Payload;

    /**
     * Summary 是一句给人看的中文（「把「中值定理」改名为「微分中值定理」」）。
     * 
     * 它由**我们**在提议时写好，不是模型的原话。这是有意的：用户点头之前读到的
     * 应当是一句陈述事实的话（改哪个、波及多少），而不是模型的劝说。模型只提供
     * 动作、参数与 Reason。
     */
    "Summary": string;

    /**
     * Reason 是模型自己交代的为什么这么改。它是给人参考的，不参与任何校验。
     */
    "Reason": string;
}

/**
 * Payload 是一条改动的载荷 —— 干这件事需要的那几个参数。
 * 
 * 一个结构体罩住四种动作，而不是每种动作一个类型：它要能原样存成 pending_changes.payload
 * 里的一段 JSON（迁移 5 的注释：拆成一堆列就会长出一片「这条改动用不上」的空列）。
 * 哪个动作用得上哪几个字段，由 Validate 说清楚。
 */
export interface Payload {
    /**
     * ParentID 是新标签的父节点。0 表示顶层学科（库里存 NULL）—— 与标签包同一个约定。
     */
    "parent_id"?: number;

    /**
     * TagID 是被改 / 被删的那个标签。
     */
    "tag_id"?: number;

    /**
     * QuestionID 是被打标签的那道错题。
     */
    "question_id"?: number;

    /**
     * Name 是标签名（新建、改名用）。
     */
    "name"?: string;

    /**
     * TagIDs 是 tag_question 要换上的那组标签。**整体替换**，空集表示摘掉全部 ——
     * 与 tags.SetQuestionTags 同一个语义（界面上是勾选，保存时把勾选结果整份交上来）。
     * 
     * 刻意**没有 omitempty**：空集与「没说」是两件事，而这条改动里它们的意思差得很远
     * （摘掉全部 vs 参数缺了）。payload 存成 JSON 再读回来，omitempty 会把前者变成后者，
     * 于是用户点「批准」时会撞上一句莫名其妙的「缺 tag_ids」。
     */
    "tag_ids": number[] | null;
}

/**
 * PendingChange 是一条**已经记下来**的待批准改动：内容 + 身份 + 状态。
 * 
 * 为什么不直接把 Change 嵌进来：这个类型是给前端的（Wails 生成的 TS 模型），
 * 嵌一层就多一层要拆的包装。字段重了四个，值那点重复。
 */
export interface PendingChange {
    "ID": number;
    "Action": Action;

    /**
     * Payload 是这条改动的参数。JSON 往返之后 tag_ids 会变成 null 而不是缺项 ——
     * 见 Payload.TagIDs 上那段说明。
     */
    "Payload": Payload;
    "Summary": string;
    "Reason": string;
    "Status": Status;

    /**
     * CreatedAt 是 agent 提议的那一刻，DecidedAt 是用户点头 / 丢弃的那一刻
     * （零值表示还没决定）。都是 UTC，与库里其它时间戳同一个约定。
     */
    "CreatedAt": string;
    "DecidedAt": string;

    /**
     * Problem 非空表示**上一次批准没成功**，这里是原因（比如「标签不存在」——
     * 行写得久了，那个标签可能已经被删了）。此时 Status 仍是 pending：
     * 那一步确实没发生，不能因为试过一次就把它标成已生效。
     */
    "Problem": string;
}

/**
 * Status 是一条待批准改动的状态。
 * 
 * 只有三种，也就是 pending_changes.status 上 CHECK 的那三个：
 * 
 * 	pending    等用户点头。**批准失败之后仍然停在它**（见 Pending.Approve）。
 * 	applied    已经写进正式数据了。
 * 	discarded  用户不要它。
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusPending = "pending",
    StatusApplied = "applied",
    StatusDiscarded = "discarded",
};
