// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Pending 是「待批准改动」这一面对前端暴露的样子。
 * 
 * 它同时是那条**唯一的写路径**的守门人：Approve 是唯一会调到 Applier 的地方，
 * 而 Applier 是唯一会写正式数据的地方。所以「绕过待批准层」在这套类型里不是被禁止的，
 * 是**不存在**的 —— 没有第二个持有 Applier 的东西，也没有第二个能执行 Change 的东西。
 * 
 * 它从不跟模型说话：模型建议什么由 agent.Service 收下，这个类型只管那些已经躺在
 * pending_changes 里的行。两半各管一段，中间隔着用户的一次点击。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Approve 批准一条改动：把它写进正式数据，然后标成已生效。
 * 
 * 三种结果，区别很重要：
 * 
 *   - 成功：返回的那条 Status 是 applied，正式数据已经改了。
 *   - **执行失败**（标签已经被删了、错题已经不在了）：error 为 nil，返回的那条
 *     Problem 里是原因、状态仍旧停在 pending。这不是「调用失败」，是「这一条现在做不了」
 *     —— 用户该看到原因并且还能再试或者丢掉它。用 error 表达的话 Wails 会把返回值一起
 *     丢掉，于是界面既不知道原因也拿不回那条记录（与 vlm.TagSuggestion.Problem 同一个理由）。
 *   - 请求本身不成立（id 不存在、已经决定过了）：这才是 error。
 * 
 * 已经生效 / 已丢弃的再批一次返回 ErrNotPending：不做幂等。
 * 「已经生效了还批准一次」与「已经丢掉了又批准」是两件对不上的事，悄悄成功只会掩盖它。
 */
export function Approve(id: number): $CancellablePromise<$models.PendingChange> {
    return $Call.ByID(2548470820, id);
}

/**
 * Count 返回还没决定的条数。界面上那个「待批准 N 条」要的就是它。
 */
export function Count(): $CancellablePromise<number> {
    return $Call.ByID(3477916518);
}

/**
 * Discard 丢掉一条改动：它不再出现在待批准列表里，正式数据一点没动。
 * 
 * 丢掉一条**不影响**别的待批准改动，更不影响已经生效的那些 —— 每一条都是一个独立的
 * 事务性决定，这里从头到尾只碰它自己那一行。
 * 
 * 已经丢过的再丢一次是**幂等**的（返回那条记录，不报错）：界面上连点两下、或者列表
 * 还没刷新时又点了一下，都不该看到一句错。
 */
export function Discard(id: number): $CancellablePromise<$models.PendingChange> {
    return $Call.ByID(2014910739, id);
}

/**
 * List 返回还没决定的那些待批准改动，早的在前。
 * 
 * 早的在前而不是新的在前：这是一份**积压的活**，要按用户提出的顺序一条条过。
 * 前端要「新的在前」可以自己翻 —— 而服务这一侧给出的是它本来的顺序。
 * 
 * 空切片而不是 nil：前端要拿到 []，不是 null。
 */
export function List(): $CancellablePromise<$models.PendingChange[] | null> {
    return $Call.ByID(3523269479);
}

/**
 * Propose 记下一条待批准改动。它是 Proposer 的实现，也就是 agent 那条路的出口。
 * 
 * **它不改动任何正式数据**：写的只有 pending_changes 里的一行。
 */
export function Propose(c: $models.Change): $CancellablePromise<$models.PendingChange> {
    return $Call.ByID(3378791387, c);
}
