// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「问 agent 一句话」那一面对前端暴露的样子，也是本包唯一的测试缝（见 spec）。
 * 
 * 它手里的四样东西没有一样能写正式数据：reader 只读、proposer 只往待批准表里写、
 * model 只会说话、configPath 是个路径。这正是包注释里那条性质的落点。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Ask 问 agent 一句话：它自己去查数据，然后回答，或者提一条待批准改动。
 * 
 * **只读 + 只提议**：这一步不会改动任何正式数据。它会往 pending_changes 里写行
 * （那是「提议」这个动作本身），但那些行要等用户逐条点头才生效。
 * 
 * streamID 由界面编好传进来，只为让这一轮的回答边生成边显示（见 vlm.StreamDelta）；
 * 传空串就是不流式、等整条回来。它不影响返回的东西 —— 界面拿去做最终显示与落点判断的
 * 永远是下面那个 Answer，流出去的分片只是给眼睛看的。
 * 
 * 没配 VLM 返回 vlm.ErrNotConfigured；问的是空的返回 ErrEmptyQuestion。
 */
export function Ask(question: string, streamID: string): $CancellablePromise<$models.Answer> {
    return $Call.ByID(822749896, question, streamID);
}
