// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";

/**
 * QueueItem 是复习队列里的一条：一道错题，加上它现在的到期时刻。
 * 
 * 题本身整个带回来（而不是只给一个 id）是因为复习界面要用它的两个 hash 去取题图与答案图
 * —— 只给 id 的话，界面每显示一道题都得再问一次题库。library.Question 是前端到处都在用的
 * 那个类型，带回来也让 AnswerBadge / hasAnswer 这些现成的东西直接吃得下。
 */
export interface QueueItem {
    /**
     * 题图 hash、答案图 hash、创建时间
     */
    "Question": library$0.Question;

    /**
     * 到期时刻。从没复习过的题没有状态，这里就是它的创建时间 ——
     * 「刚拍完就出现在队列里」（story 12）与「拖了很久的题排在最前」是同一句话。
     */
    "DueAt": string;
}

/**
 * Rating 是复习后自评的四档，也是喂给 FSRS 的唯一输入。
 * 
 * 取值刻意与 fsrs.Rating 相同（1..4）：落库时照这个存，schema 的 CHECK 就直接是
 * 「必须是这四档之一」，中间不必再维护一张映射表。
 */
export enum Rating {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * 完全没想起来
     */
    Again = 1,

    /**
     * 想起来了，但很费劲
     */
    Hard = 2,

    /**
     * 想起来了
     */
    Good = 3,

    /**
     * 太简单，不用再排这么密
     */
    Easy = 4,
};

/**
 * ReviewResult 是一次复习的结果：喂进去的评级，和 FSRS 算出来的下一次到期。
 * 
 * 与服务端落库的那两行是同一个来源 —— 界面拿它显示「下次：3 天后」，不必再回库问一次。
 */
export interface ReviewResult {
    "QuestionID": number;
    "Rating": Rating;

    /**
     * 这次复习的时刻
     */
    "ReviewedAt": string;

    /**
     * 下次到期
     */
    "DueAt": string;

    /**
     * 当时算出的间隔（天）
     */
    "ScheduledDays": number;
}
