// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「复习」对前端暴露的那一面，也是本包唯一的测试缝（见 spec）。
 * 
 * 它持有一条错题库连接（复习状态与错题同一份库文件）与题库本身 —— 写之前要确认这道题在，
 * 那条查询在 library 那边，不必在本包再抄一遍 SQL。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Config 返回当前的复习参数设置（含四档预览）；文件坏了就退回默认值，并把问题带回去。
 * 
 * 每次都**重读一遍文件**，不只读缓存：这一页是用户改设置的地方，它显示的必须是他刚存下的
 * 那一份。顺带把缓存也刷新了 —— 排程与界面看到的因此是同一个值。
 */
export function Config(): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(3590061656);
}

/**
 * Grade 记录一次复习：把评级交给 FSRS 算出下一次到期，落库，并把结果带回来。
 * 
 * 题不存在返回 library.ErrNotFound，评级不是四档之一返回 ErrInvalidRating；
 * 两种情况都不落任何写入。
 * 
 * 刻意**不检查「这道题现在到期了吗」**：界面只把到期的题端上来，但用户也可能从题库页
 * 点进来复习一道还没到期的题 —— 那是他的选择，不是错误。评级照样从此刻往后排。
 */
export function Grade(questionID: number, rating: $models.Rating): $CancellablePromise<$models.ReviewResult> {
    return $Call.ByID(2156260513, questionID, rating);
}

/**
 * Preview 按**传进来的这份设置**算一遍视图：不落盘、不动库、也不改缓存。
 * 
 * 为什么值得单开一个方法，而不是等 SetConfig 的返回值：这一页唯一要回答的问题是
 * 「这么设之后间隔变多长」，而那个答案要在按下保存**之前**就看得见 —— 否则每试一个日期
 * 都是一次真的写入（还会顺手拉一批到期日回来）。
 * 
 * 日期不合法时返回错误，界面那侧静默退回「按已保存那份显示」：用户还在打字的中间，
 * 一个打了一半的日期不该弹一句红字。
 */
export function Preview(c: $models.Config): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(3834838082, c);
}

/**
 * Queue 返回当前的**今日复习队列**：到期日是今天或更早的错题，最该复习的在前。
 * 
 * 队列的长度就是「今天还剩多少道」—— 评过的题会把到期推到至少明天（见 Config.params），
 * 所以做完一道它就少一道，中途重进本页也不会把刚做过的捞回来。
 * 
 * 判定按**本地日**取，取到次日零点为止（endOfToday）。这么定的理由、以及它与「到期其实
 * 是一个时刻」之间的关系，写在 endOfToday 上 —— 那是本包唯一涉及时区的地方。
 */
export function Queue(): $CancellablePromise<$models.QueueItem[] | null> {
    return $Call.ByID(1015212025);
}

/**
 * SetConfig 存下复习参数，并把库里已经排到生效上限之外的到期日拉回来。
 * 
 * 拉回来放在这里、而不是每次算调度参数时顺手做，因为那是一个**用户动作**的结果
 * （他填了或者改了考试日期）：要能给他一个「动了几道」的数字，而且不该天天偷偷改库。
 * 
 * 顺序是先落盘再动库 —— 反过来的话会留下「库已经被改了，而设置没存下去」的状态，
 * 那个上限下次就没人记得，被拉的题白拉。
 */
export function SetConfig(c: $models.Config): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(719005648, c);
}
