// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「复习」对前端暴露的那一面，也是本包唯一的测试缝（见 spec）。
 * 
 * 它持有一条错题库连接（复习状态与错题同一份库文件）与题库本身 —— 写之前要确认这道题在，
 * 那条查询在 library 那边，不必在本包再抄一遍 SQL。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Grade 记录一次复习：把评级交给 FSRS 算出下一次到期，落库，并把结果带回来。
 * 
 * 题不存在返回 library.ErrNotFound，评级不是四档之一返回 ErrInvalidRating；
 * 两种情况都不落任何写入。
 * 
 * 刻意**不检查「这道题现在到期了吗」**：界面只把到期的题端上来，但用户也可能从题库页
 * 点进来复习一道还没到期的题 —— 那是他的选择，不是错误。评级照样从此刻往后排。
 */
export function Grade(questionID: number, rating: $models.Rating): $CancellablePromise<$models.ReviewResult> {
    return $Call.ByID(2156260513, questionID, rating);
}

/**
 * Queue 返回当前的**今日复习队列**：到期日是今天或更早的错题，最该复习的在前。
 * 
 * 队列的长度就是「今天还剩多少道」—— 评过的题会把到期推到至少明天（见 newScheduler），
 * 所以做完一道它就少一道，中途重进本页也不会把刚做过的捞回来。
 * 
 * 判定按**本地日**取，取到次日零点为止（endOfToday）。这么定的理由、以及它与「到期其实
 * 是一个时刻」之间的关系，写在 endOfToday 上 —— 那是本包唯一涉及时区的地方。
 */
export function Queue(): $CancellablePromise<$models.QueueItem[] | null> {
    return $Call.ByID(1015212025);
}
