// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bundle 是一个**已经打好、等人把它搬出去**的导出包。
 */
export interface Bundle {
    /**
     * Path 是包在应用私有目录里的落点：宿主读它，搬完把源文件删掉。
     */
    "Path": string;

    /**
     * Name 是建议的显示名，宿主拿它当「下载」目录里的文件名。
     */
    "Name": string;

    /**
     * 库里的错题数
     */
    "Questions": number;

    /**
     * 打进包里的图片张数（按内容 hash 去重之后）
     */
    "Images": number;

    /**
     * 包的字节数
     */
    "Bytes": number;
}
