// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Config 是每日汇总通知的设置。**不进 SQLite**。
 * 
 * 它照的是 vlm 那份配置的做法（库外 JSON，与 library.db 并列），理由也一样：
 * 配置不属于错题的数据模型，也不该跟着导出包被打包到别的手机上 ——
 * 「这个手机上的提醒设在晚上八点」对换手机的人没有意义。
 */
export interface Config {
    /**
     * Enabled 是总开关（ticket 的验收项：用户能关掉它）。
     * 
     * 关掉之后排程文件里会写成 enabled:false 且 slots 为空（见 Schedule.Enabled），
     * 那是宿主唯一需要看的一件事 —— Go 没有别的渠道能通知到它，见 Service.Refresh。
     */
    "enabled": boolean;

    /**
     * Hour / Minute 是每天发的那一刻，本地时间。
     * 
     * 它是个**钟点**不是时刻：换时区之后提醒跟着新时区走。范围由 Validate 卡住。
     */
    "hour": number;
    "minute": number;
}

/**
 * ConfigView 是设置的「界面版」。
 * 
 * 与 vlm 那个不同，这里**没有**「凭据只出不进」那回事：这份设置没有任何秘密，
 * 界面拿到是真的值，也是真的值传回来（见 Service.SetConfig）。
 */
export interface ConfigView {
    /**
     * Path 是设置文件的落点、SchedulePath 是排程文件的落点。
     * 
     * 两个都显示出来是因为安卓上这些路径用户平时够不着，出问题时至少知道该去哪儿找
     * （与 vlm 的 ConfigView.Path 同一个理由）。排程那份尤其值得露出来：
     * 它才是宿主真正读的东西，「我明明开着提醒可它就是不响」第一个要看的就是它。
     */
    "Path": string;
    "SchedulePath": string;
    "Enabled": boolean;
    "Hour": number;
    "Minute": number;

    /**
     * HorizonDays 是排程预算的天数，界面拿它说清「这份预告能撑多久」。
     */
    "HorizonDays": number;

    /**
     * Problem 非空时说明设置文件有问题（读不了、写坏了），此时上面几项是**默认值** ——
     * 界面不是白的，用户还能把它改回去。
     */
    "Problem": string;

    /**
     * Host 是宿主（Java 那一侧）回写的状态，HostNote 是它翻成的一句人话（可能为空）。
     * 
     * 为什么分成两样：界面要的只是 Note，而 Host 留着以后做更细的诊断（比如「上次真发的
     * 是哪一刻」）。两者都是**诊断**，读不到时 Host.Known 为 false、Note 为空 ——
     * 那种情况下界面什么都不该说，因为「宿主没报过」不是用户的错。
     */
    "Host": HostStatus;
    "HostNote": string;
}

/**
 * DayCount 是某一天到期的错题数。
 */
export interface DayCount {
    /**
     * Date 是本地日，形如 "2026-09-16"。
     */
    "Date": string;

    /**
     * Count 是**那一天结束时**累计到期的错题数：含更早欠下的。
     * 
     * 口径与复习队列一致（review.Service.Queue 取的也是「到期日不晚于今天的全部」），
     * 所以通知上的数字与用户点进去看到的队列长度是同一个 —— 汇总说 5 道、
     * 点进去只有 3 道，是这条口径在撑着的两处必须对齐的理由。
     */
    "Count": number;
}

/**
 * HostStatus 是**宿主**（Java 那一侧）回写的状态。
 * 
 * 为什么要有它：有两件事 Go 侧无从知道 —— 系统里的通知权限有没有被关、精确闹钟的
 * 「闹钟和提醒」权限有没有给。那两件事只有 Java 知道（`areNotificationsEnabled()`、
 * `canScheduleExactAlarms()`），所以由它每次 arm / 发完之后写进一个文件，这里只读。
 * 
 * **读不到、读坏了都不算错。** 这份东西是诊断，缺了它设置页少显示一行而已；
 * 让它报错会把「提醒设置」整页顶成红色，而用户其实什么都没做错。
 */
export interface HostStatus {
    /**
     * Known 为 false 表示宿主还没写过这个文件（补丁还没打上，或者装上之后
     * 宿主那一侧一次都没跑过）。此时下面几项没有意义，界面也不该拿它们说事。
     */
    "Known": boolean;

    /**
     * CanScheduleExact 是「闹钟和提醒」权限。false 不等于发不出来 —— 宿主会降级到
     * 不精确的窗口闹钟，只是可能被系统省电策略推到维护窗口。
     */
    "CanScheduleExact": boolean;

    /**
     * NotificationsEnabled 是系统里的通知权限。false 就是**真的发不出来**。
     */
    "NotificationsEnabled": boolean;
    "LastArmAtMS": number;
    "LastFireAtMS": number;

    /**
     * LastResult 取值由宿主那边定：posted / skipped_disabled / skipped_no_due /
     * skipped_stale / skipped_no_permission / failed。空串 = 还没发过。
     */
    "LastResult": string;
}

/**
 * Schedule 是交给宿主的那份排程：未来 HorizonDays 天里哪天几点发、发什么。
 * 
 * 它是**只读给宿主**的一份快照。宿主不读数据库、不读设置文件，只读它 —— 那正是
 * 「宿主不必引一套 SQLite」这句话的落点。
 */
export interface Schedule {
    /**
     * Enabled 为 false 时 Slots 一定是空的：关掉这件事在两处同时说出来，
     * 宿主少判一个条件就少一次误发的机会。
     */
    "Enabled": boolean;
    "Hour": number;
    "Minute": number;

    /**
     * GeneratedAt 是这份排程算出来的时刻。宿主可以据此判断它有多旧。
     */
    "GeneratedAt": string;

    /**
     * Slots 从最近的一次算起，一天一条。空切片而不是 nil（前端要拿到 []，不是 null）。
     */
    "Slots": Slot[] | null;
}

/**
 * Slot 是一次汇总：什么时候发、发什么。
 */
export interface Slot {
    /**
     * FireAt 是这次该发的时刻。它是一个**定时钟点**在某个本地日上的落点
     * （那一天的 Hour:Minute），不是「从现在算起的第几毫秒」。
     */
    "FireAt": string;

    /**
     * Date 是那一天的本地日，形如 "2026-09-16"。
     * 
     * 宿主拿它核对「我发的确实是这一天的」：闹钟可能被系统推迟到第二天才醒，
     * 那时候这条就不该再发了（也正是靠它，宿主能分辨「今天没有到期题」与
     * 「这份排程根本没覆盖今天」）。
     */
    "Date": string;

    /**
     * Count 是这一天到期的错题数；**0 表示到点不发**（ticket：当天没有到期题则不发）。
     */
    "Count": number;

    /**
     * Title / Body 是这条通知要显示的字，Go 侧就算好。
     * 
     * 放在这里而不是让宿主自己拼：验收项「内容包含当天到期的数量」于是能在 Go 的测试里
     * 钉住，而不是散在 Java 里没法测 —— 宿主那一侧只有「念出来」一件事。
     */
    "Title": string;
    "Body": string;
}
