// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「每日汇总通知」对前端暴露的那一面，也是本包唯一的测试缝（spec：
 * 全应用只有一条缝，在服务层）。它同样只有这一面 —— 宿主那一侧读的是磁盘上的
 * 排程文件，不调这里任何方法（宿主是 Java，调不动 Go）。
 * 
 * 它做的事有两条线：往下是「某个本地日到期多少」，往上是「未来若干天什么时候发、发什么」。
 * 两条线都只是**算**：本包不改任何错题数据，也不写库。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Config 返回设置的「界面版」。
 * 
 * 读不到也要给一份视图（与 vlm 的 Config 同一个立场）：界面正是靠 Problem 告诉用户
 * 那个文件怎么了。文件**不在**不算问题 —— 那是「还没配过」，显示默认值（开着、20:00）。
 */
export function Config(): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(3948595348);
}

/**
 * Forecast 返回从今天起 days 天里，每一天到期的错题数。
 * 
 * 「每一天」是**本地日**，边界是那一天的次日零点（见 endOfDay），Count 是累计到那一刻
 * 的数量 —— 含更早欠下的，与复习队列同一口径（见 DayCount.Count）。
 * 
 * days 会被收进 [1, 31]（见 clampDays）：这是个「算多久」的量，不是用户输入的数据。
 * 
 * 这个方法**只读不写**：它不落盘、不碰设置，随便调。
 */
export function Forecast(days: number): $CancellablePromise<$models.DayCount[] | null> {
    return $Call.ByID(1747502363, days);
}

/**
 * Next 返回下一次该发的那一条：什么时候发、那一天到期多少、发什么字。
 * 
 * 它**永远有值**：时刻是定死的（今天 cfg.Hour:cfg.Minute，这个点过了就是明天的同一时刻），
 * 到点会不会真发看 Count —— 0 就是不发（当天没有到期题）。所以这里没有「有没有下一次」
 * 这种问题，也不需要第二个返回值。
 * 
 * 它不落盘（要看落盘的那份用 Refresh）。
 */
export function Next(): $CancellablePromise<$models.Slot> {
    return $Call.ByID(288084535);
}

/**
 * Refresh 重算未来 HorizonDays 天的排程，落盘，并把刚写下的那份带回来。
 * 
 * 这是本包唯一写盘的地方，也是**宿主那份文件的唯一来路**。它得被这几处调到：
 * 应用打开时、设置保存时（SetConfig 内部已经调了）、以及应用退到后台时 ——
 * 最后那一处是必要的：用户在退出去之前刚评过几道题，那些新的到期时刻只有到这一刻
 * 才落进排程里；不重算的话，第二天那条通知报的数字就少了几道。
 * 
 * 关掉时写出去的是 enabled:false 加空的 slots（见 Schedule.Enabled）。这是「别发了」
 * 传达到宿主的**唯一**一条路：宿主是另一个进程里的 Java，Go 这边没有任何办法去叫它
 * 取消一个已经排好的闹钟，只能把话写进它到点会读的那个文件里。
 * 
 * 设置文件坏了（不是「不在」）时返回错误且**不写盘**：说不出该几点发，就不该拿默认值
 * 悄悄顶替 —— 用户明明配过，被换成 20:00 只会让人以为设置丢了。留下上一份排程还能发，
 * 而界面会把 Problem 显示出来让用户改回去。
 */
export function Refresh(): $CancellablePromise<$models.Schedule> {
    return $Call.ByID(3506006193);
}

/**
 * SetConfig 把设置写下去，并立刻重算排程。
 * 
 * 传进来的是**整份**设置，不是补丁 —— 与 vlm.SetConfig 刻意不同。那边是补丁，因为
 * 界面拿不到凭据的值，整份覆盖会把 key 抹掉；这里没有任何秘密，界面读到的是真值，
 * 也就能把整份原样送回来。补丁语义在布尔量上还会直接坏掉：「关掉」与「没提这一项」
 * 都是 false，分不开。
 * 
 * 先验再写：一个 25 点的时刻存下去也算不出排程，不如当场退回，别让它躺在盘上。
 * 写完立刻 Refresh 是**这个方法的重点**：关掉提醒这件事只有落进排程文件才算数
 * （Go 没有别的渠道能通知到宿主，见 Refresh）。
 */
export function SetConfig(cfg: $models.Config): $CancellablePromise<void> {
    return $Call.ByID(474572948, cfg);
}
