// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Point 是图像像素坐标系里的一个点：原点在左上角，X 向右、Y 向下。
 */
export interface Point {
    "X": number;
    "Y": number;
}

/**
 * Quad 是用户拖出的四个角点，顺序固定为 左上 → 右上 → 右下 → 左下。
 * 
 * 顺序就是一切：它不要求是矩形、不要求轴对齐，甚至不要求凸 —— 透视拉正
 * 存在的意义正是抹平这个歪掉的四边形。反过来，顺序错了（比如把角点按
 * 顺时针传成了逆时针），拉正结果就是翻转或自交的，这里只能报错拦不住。
 */
export type Quad = Point[];
