// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「采集」对前端暴露的那一面，也是这条链路上唯一的测试缝（见 spec）。
 * 
 * 它只做搬运与编解码：真正的活（透视拉正、按内容 hash 落盘）在 Rectify 与 Store 里。
 * 拆开是为了让那两样能在不启动 Wails 的情况下被测 —— NewService 出来的东西照样能直接调。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Card 按 hash 取回卡片图，返回 PNG 的 base64 供界面显示。
 * 
 * 一律编成 PNG：卡片图是**原始像素**，不能再过一次有损编码（spec 的 Out of Scope）。
 */
export function Card(hash: string): $CancellablePromise<string> {
    return $Call.ByID(509030524, hash);
}

/**
 * Rectify 收一张帧（PNG 或 JPEG 的 base64）与四个角点，透视拉正后按内容 hash 落盘，返回该 hash。
 * 
 * 角点坐标是**相对传入这张图**的像素坐标，顺序固定为 左上 → 右上 → 右下 → 左下（见 Quad）。
 * 前端应当先按预览可见区裁好再传 —— 传整张传感器画面会白白多走一大截带宽与内存。
 */
export function Rectify(frameBase64: string, quad: $models.Quad): $CancellablePromise<string> {
    return $Call.ByID(1263547862, frameBase64, quad);
}
