// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Pending 描述一个已经就绪、等下次启动落地的导入。
 */
export interface Pending {
    "Ready": boolean;
    "Preview": Preview;
    "PreparedAt": string;
}

/**
 * Picked 是一次「挑一个包」的结果。
 * 
 * 取消做成**正常结果里的一个字段**，而不是一个错误：用户点了取消什么都没发生，
 * 界面不该弹一句红的。做成错误的话前端只能去认错误文案，而文案一改就坏。
 */
export interface Picked {
    /**
     * Cancelled 为真表示用户取消了（或者什么都没选），此时 Preview 是零值。
     */
    "Cancelled": boolean;
    "Preview": Preview;
}

/**
 * Preview 是一个已经解好、校验过的包，等人点头。
 */
export interface Preview {
    /**
     * 包里有多少道错题
     */
    "Questions": number;

    /**
     * 包里有多少张图（去重后）
     */
    "Images": number;

    /**
     * zip 文件本身有多大
     */
    "Bytes": number;

    /**
     * Settings 是包里带的那几份库外设置（目前是 review.json / digest.json）。
     * 空切片表示这个包只有库与图。
     */
    "Settings": string[] | null;

    /**
     * Current 是**现在**库里的错题数。单独列出来，是因为确认框真正该给人看的是
     * 「包里 42 道 / 你现在 57 道」这个对比 —— 只说前者，用户点下去之前没法判断
     * 自己是不是在拿一份旧备份盖掉新数据。
     */
    "Current": number;
}

/**
 * Result 是落地那一步的结果：成功也好、失败了也好，都写下来给界面看。
 * 
 * 失败也要留痕，是因为这一步在启动时跑，那时没有任何界面在场 —— 用户唯一能知道
 * 「上次导入没成」的地方就是这里。
 */
export interface Result {
    "OK": boolean;
    "Questions": number;
    "Images": number;
    "At": string;

    /**
     * Backup 是旧库被挪到哪儿了（空串表示本来就没有旧库）。
     * 有它才说得清「你的旧数据还在」。
     */
    "Backup": string;

    /**
     * Problem 非空表示这次落地失败了，这里是原因。
     */
    "Problem": string;
}
