// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是「从导出包恢复」对前端暴露的那一面。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel 丢掉暂存目录里那个还没落地的导入。没有待落地的也算成功 ——
 * 调用方要的是「它不在了」，而它确实不在。
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(1120092246);
}

/**
 * Commit 给这次导入盖上「用户确认过了」的章，之后它会在下次启动落地。
 * 
 * 到这一步仍然**没有动正式数据**。盖章与落地分开，是因为落地只能在启动时做
 * （见包注释），而用户点头与下次启动之间可能隔着很久 —— 中间他还能反悔（Cancel）。
 */
export function Commit(): $CancellablePromise<void> {
    return $Call.ByID(4238382369);
}

/**
 * Last 读回上一次落地的结果。从没落地过就返回零值（OK 为 false）。
 */
export function Last(): $CancellablePromise<$models.Result> {
    return $Call.ByID(1827317652);
}

/**
 * Pending 报告当前有没有等落地的导入。没有的话 Ready 为 false。
 */
export function Pending(): $CancellablePromise<$models.Pending> {
    return $Call.ByID(4268498143);
}

/**
 * PickAndPrepare 让用户挑一个导出包，解出来校验好，摆进暂存目录。
 * 
 * 它**不动正式数据**：通过的话要用户再点一次确认（Commit），然后在下次启动才落地。
 * 这中间用户随时可以 Cancel 掉。
 */
export function PickAndPrepare(): $CancellablePromise<$models.Picked> {
    return $Call.ByID(3211067165);
}
